# production configuration

version: '2.1'
services:
  eureka-peer:
    extends:
      service: base-eureka
      file: docker-compose-base.yml
    container_name: ${CONTAINER_HOST_NAME:-eureka-peer1}
    environment:


    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    - EUREKA_INSTANCE_HOSTNAME=${HOST_IPADDRESS} # ${CONTAINER_HOST_NAME:-eureka-peer1}
    - EUREKA_INSTANCE_IPADDRESS=${HOST_IPADDRESS}
    - EUREKA_INSTANCE_NONSECUREPORT=${SERVER_PORT:-8761}


    - EUREKA_SERVER_ENABLESELFPRESERVATION=${EUREKA_SERVER_ENABLESELFPRESERVATION:-true}
    - EUREKA_SERVER_RENEWALPERCENTTHRESHOLD=${EUREKA_SERVER_RENEWALPERCENTTHRESHOLD:-0.50}
    - INSTANCE_NAME=${CONTAINER_HOST_NAME:-eureka-peer1}
    - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT:-INFO}

    - SECURITY_USER_NAME=${SECURITY_USER_NAME:-user}
    - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD:-user_pass}
    - SERVER_PORT=${SERVER_PORT:-8761}
    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-eureka-cluster}
    - SPRING_CLOUD_CLIENT_HOSTNAME=${HOST_IPADDRESS} # ${CONTAINER_HOST_NAME:-eureka-peer1}
    - SPRING_CLOUD_CLIENT_IPADDRESS=${HOST_IPADDRESS}
    - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-staging.env,manual_ip_hostname,port_nonsecure,peer_awareness}
    hostname: ${CONTAINER_HOST_NAME:-eureka-peer1}
    network_mode: bridge
    ports:
    - "${SERVER_PORT:-8761}:${SERVER_PORT:-8761}"
    volumes:
    - data:/root/data
    - data:/tmp

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
