# local development configuration

version: '2.1'
services:
  eureka-sidecar-develop:
    extends:
      file: docker-compose-base.yml
      service: base-eureka-sidecar
    container_name: ${CONTAINER_HOST_NAME:-eureka-sidecar}
    environment:
    - EUREKA_INSTANCE_PREFERIPADDRESS=${EUREKA_INSTANCE_PREFERIPADDRESS:-false}
    - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT:-INFO}
    - SERVER_PORT=${SERVER_PORT:-5678}
    - SIDECAR_HEALTHURI=${SIDECAR_HEALTHURI:-http://standalone.eureka:8761/actuator/health}
    - SIDECAR_HOMEPAGEURI=${SIDECAR_HOMEPAGEURI:-http://standalone.eureka:8761}
    - SIDECAR_HOSTNAME=${SIDECAR_HOSTNAME:-standalone.eureka}
    - SIDECAR_IPADDRESS=${SIDECAR_IPADDRESS} # Optional
    - SIDECAR_PORT=${SIDECAR_PORT:-8761}
    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-the-name-of-non-JVM-application-or-service}
    - SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USER_NAME:-user}
    - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD:-user_pass}
    hostname: ${CONTAINER_HOST_NAME:-eureka-sidecar}
    ports:
    - "${SERVER_PORT:-5678}:${SERVER_PORT:-5678}"
    networks:
      local-network:
        ipv4_address: 172.16.238.78
        #ipv6_address: 2001:3984:3989::78
    volumes:
    - data:/home/alpine/data
    - tmp:/tmp

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  tmp:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/tmp
      o: bind
